# GoMCP Framework Configuration File
# This file defines agents, registries, servers, and tools using simple YAML syntax

# API Key for authentication (also checks AGENTCONFIG env variable)

# LBCC Week 6 Group Final Project: Construction Schedule Assistant
# This configuration powers the automated project scheduler for the Health Occupations Center Phase II

agents:
  - agent_id: "agent for anthony "
    description: "you are an agent that helps Anthony with his daily life"
    
    llm:
      api_key: 
      model: "gpt-4o-mini"
      temperature: 0.3
      max_tokens: 2048
    servers:
      - 'C:\Users\antho\GoMCP\serverconfigs\server2config.yaml'
      - 'C:\Users\antho\GoMCP\serverconfigs\server1config.yaml'